openapi: 3.1.0
info:
  title: SAP MARA
  description: 
  version: '2.2'
paths:
  /material:
    get:
      responses:
        200:
          description: '200 response description'
          content:
            application/json:
              example:
                - matnr: "450001"
                  desc: "筆"
                - matnr: "450002"
                  desc: "盒子"
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    matnr:
                      description: '料號'
                      type: string
                    desc:
                      description: '說明'
                      type: string
      description: 'get material information'
      deprecated: false