openapi: 3.1.0
info:
  title: SAP MARA
  description: SAP 料號資料
  version: '2.2'
servers:
  -
    url: 'http://221.224.123.238:9527/api/MARA/GetMatnr/ZX000000'
paths:
  /posts:
    get:
      responses:
        200:
          description: '200 response description'
          content:
            application/json:
              schema: 
                type: object
                properties:
                  ReturnMsg:
                    description: '回傳訊息'
                    type: string
                  MATNR:
                    description: '物料編號'
                    type: string
                  MAKTX:
                    description: '物料描述'
                    type: string
      description: 'get use responses'
      deprecated: false