openapi: 3.1.0
info:
  title: SAPf料號參考
  version: 1.0.0
  description: 提供天氣預報資料的API
servers:
  - url: https://opendata.cwa.gov.tw
paths:
  /weather:
    get:
      summary: 獲取天氣資料
      description: 根據地點名稱獲取天氣預報資料
      parameters:
        - name: locationName
          in: query
          required: true
          description: 地點名稱
          schema:
            type: string
      responses:
        '200':
          description: 成功獲取天氣資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/weatherData'
components:
  schemas:
    weatherData:
      type: object
      properties:
        datasetDescription:
          type: string
          description: datasetDescription
        locationName:
          type: string
          description: locationName
        parameterName:
          type: string
          description: parameterName
        parameterValue:
          type: string
          description: parameterValue        
        parameterUnit:
          type: string
          description: parameterUnit    
        startTime:
          type: string
          format: date-time
          description: startTime   
        endTime:
          type: string
          format: date-time
          description: endTime
      example: # 正確添加單個範例物件
        datasetDescription: "36小時天氣預報"
        locationName: "台北市"
        parameterName: "天氣狀況"
        parameterValue: "多雲時晴"
        parameterUnit: ""
        startTime: "2023-04-01T00:00:00Z"
        endTime: "2023-04-02T12:00:00Z"