openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
servers:
  - url: https://opendata.cwa.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON
paths:
  /coffee/hot:
    get:
      summary: Get 36 Hours of Weather Data
      responses:
        '200':
          description: Get 36 Hours of Weather Data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/weatherData'
components:
  schemas:
    weatherData:
      type: object
      properties: # Add the missing properties keyword
        datasetDescription:
          type: string
          description: datasetDescription
        locationName:
          type: string
          description: locationName
        parameterName:
          type: string
          description: parameterName
        parameterValue:
          type: string
          description: parameterValue        
        parameterUnit:
          type: string
          description: parameterUnit    
        startTime:
          type: Timestamp
          description: startTime   
        endTime:
          type: Timestamp
          description: endTime                                    
 