openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
servers:
  - url: https://opendata.cwa.gov.tw/api/v1/rest/datastore
paths:
  /F-C0032-001:
    get:
      summary: Get 36 Hours of Weather Data
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get 36 Hours of Weather Data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/weatherData'
components:
  schemas:
    weatherData:
      type: object
      properties:
        datasetDescription:
          type: string
          description: datasetDescription
        locationName:
          type: string
          description: locationName
        parameterName:
          type: string
          description: parameterName
        parameterValue:
          type: string
          description: parameterValue        
        parameterUnit:
          type: string
          description: parameterUnit    
        startTime:
          type: string
          format: date-time
          description: startTime   
        endTime:
          type: string
          format: date-time
          description: endTime