name: Call Web API

on: [push]

jobs:
  call-web-api:
    runs-on: ubuntu-latest
    steps:
    - name: Call Web API
      run: |
        curl -X GET 'http://192.168.1.49:7001/api/MARA/GetMaterialList/10' -H  
